version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: novel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: novel_platform
      TZ: Asia/Shanghai
    command:
      [
        "mysqld",
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_0900_ai_ci"
      ]
    ports:
      - "3306:3306"
    volumes:
      - novel-mysql-data:/var/lib/mysql
      - ./novel_platform.sql:/docker-entrypoint-initdb.d/novel_platform.sql:ro

  backend:
    build: ./novel_backened
    container_name: novel-backend
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/novel_platform?useSSL=false&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 123456
      JWT_SECRET: novel_platform_2026_default_secret
      JWT_EXPIRE_SECONDS: 86400
    ports:
      - "8080:8080"

  frontend:
    build: ./novel_fronted
    container_name: novel-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  novel-mysql-data:

